<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	</PropertyGroup>


	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Properties\**" />
    <Compile Remove="Resources\**" />
    <Compile Remove="Views\**" />
    <EmbeddedResource Remove="Properties\**" />
    <EmbeddedResource Remove="Resources\**" />
    <EmbeddedResource Remove="Views\**" />
    <None Remove="Properties\**" />
    <None Remove="Resources\**" />
    <None Remove="Views\**" />
    <Page Remove="Properties\**" />
    <Page Remove="Resources\**" />
    <Page Remove="Views\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="resourses\68fadad90ca053b59b3e0178c4983607.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Dapper" Version="2.1.86" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0-preview3.26238.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HomeNetCore\HomeNetCore.csproj" />
    <ProjectReference Include="..\HomeNetPresentation\HomeNetPresentation.csproj" />
    <ProjectReference Include="..\HomeNetServices\HomeNetServices.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="resourses\68fadad90ca053b59b3e0178c4983607.png" />
  </ItemGroup>

</Project>
